/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard/alerts'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardDetectionsRouteImport } from './routes/dashboard/detections'
import { Route as DashboardImagesRouteImport } from './routes/dashboard/images'
import { Route as DashboardIngestRouteImport } from './routes/dashboard/ingest'
import { Route as DashboardMapRouteImport } from './routes/dashboard/map'
import { Route as DashboardMovementRouteImport } from './routes/dashboard/movement'
import { Route as DashboardPipelineRouteImport } from './routes/dashboard/pipeline'
import { Route as DashboardReviewRouteImport } from './routes/dashboard/review'
import { Route as DashboardStationsRouteImport } from './routes/dashboard/stations'
import { Route as DashboardSystemRouteImport } from './routes/dashboard/system'
import { Route as DashboardTigersRouteImport } from './routes/dashboard/tigers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDetectionsRoute = DashboardDetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImagesRoute = DashboardImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIngestRoute = DashboardIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMovementRoute = DashboardMovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPipelineRoute = DashboardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewRoute = DashboardReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStationsRoute = DashboardStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemRoute = DashboardSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTigersRoute = DashboardTigersRouteImport.update({
  id: '/tigers',
  path: '/tigers',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/detections': typeof DashboardDetectionsRoute
  '/dashboard/images': typeof DashboardImagesRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/movement': typeof DashboardMovementRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/review': typeof DashboardReviewRoute
  '/dashboard/stations': typeof DashboardStationsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/tigers': typeof DashboardTigersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/detections': typeof DashboardDetectionsRoute
  '/dashboard/images': typeof DashboardImagesRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/movement': typeof DashboardMovementRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/review': typeof DashboardReviewRoute
  '/dashboard/stations': typeof DashboardStationsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/tigers': typeof DashboardTigersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/detections': typeof DashboardDetectionsRoute
  '/dashboard/images': typeof DashboardImagesRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/movement': typeof DashboardMovementRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/review': typeof DashboardReviewRoute
  '/dashboard/stations': typeof DashboardStationsRoute
  '/dashboard/system': typeof DashboardSystemRoute
  '/dashboard/tigers': typeof DashboardTigersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/detections'
    | '/dashboard/images'
    | '/dashboard/ingest'
    | '/dashboard/map'
    | '/dashboard/movement'
    | '/dashboard/pipeline'
    | '/dashboard/review'
    | '/dashboard/stations'
    | '/dashboard/system'
    | '/dashboard/tigers'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/detections'
    | '/dashboard/images'
    | '/dashboard/ingest'
    | '/dashboard/map'
    | '/dashboard/movement'
    | '/dashboard/pipeline'
    | '/dashboard/review'
    | '/dashboard/stations'
    | '/dashboard/system'
    | '/dashboard/tigers'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/detections'
    | '/dashboard/images'
    | '/dashboard/ingest'
    | '/dashboard/map'
    | '/dashboard/movement'
    | '/dashboard/pipeline'
    | '/dashboard/review'
    | '/dashboard/stations'
    | '/dashboard/system'
    | '/dashboard/tigers'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/detections': {
      id: '/dashboard/detections'
      path: '/detections'
      fullPath: '/dashboard/detections'
      preLoaderRoute: typeof DashboardDetectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/images': {
      id: '/dashboard/images'
      path: '/images'
      fullPath: '/dashboard/images'
      preLoaderRoute: typeof DashboardImagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ingest': {
      id: '/dashboard/ingest'
      path: '/ingest'
      fullPath: '/dashboard/ingest'
      preLoaderRoute: typeof DashboardIngestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/movement': {
      id: '/dashboard/movement'
      path: '/movement'
      fullPath: '/dashboard/movement'
      preLoaderRoute: typeof DashboardMovementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pipeline': {
      id: '/dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/dashboard/pipeline'
      preLoaderRoute: typeof DashboardPipelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review': {
      id: '/dashboard/review'
      path: '/review'
      fullPath: '/dashboard/review'
      preLoaderRoute: typeof DashboardReviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stations': {
      id: '/dashboard/stations'
      path: '/stations'
      fullPath: '/dashboard/stations'
      preLoaderRoute: typeof DashboardStationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system': {
      id: '/dashboard/system'
      path: '/system'
      fullPath: '/dashboard/system'
      preLoaderRoute: typeof DashboardSystemRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tigers': {
      id: '/dashboard/tigers'
      path: '/tigers'
      fullPath: '/dashboard/tigers'
      preLoaderRoute: typeof DashboardTigersRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardDetectionsRoute: typeof DashboardDetectionsRoute
  DashboardImagesRoute: typeof DashboardImagesRoute
  DashboardIngestRoute: typeof DashboardIngestRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardMovementRoute: typeof DashboardMovementRoute
  DashboardPipelineRoute: typeof DashboardPipelineRoute
  DashboardReviewRoute: typeof DashboardReviewRoute
  DashboardStationsRoute: typeof DashboardStationsRoute
  DashboardSystemRoute: typeof DashboardSystemRoute
  DashboardTigersRoute: typeof DashboardTigersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardDetectionsRoute: DashboardDetectionsRoute,
  DashboardImagesRoute: DashboardImagesRoute,
  DashboardIngestRoute: DashboardIngestRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardMovementRoute: DashboardMovementRoute,
  DashboardPipelineRoute: DashboardPipelineRoute,
  DashboardReviewRoute: DashboardReviewRoute,
  DashboardStationsRoute: DashboardStationsRoute,
  DashboardSystemRoute: DashboardSystemRoute,
  DashboardTigersRoute: DashboardTigersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
